### PR TITLE
Fix days

### LINKED ISSUE #7: Fix daysofmonth to show correct days

### PR DESCRIPTION
**Pull request by szk3y**
Fixes #7

### CODE REVIEW

File: DaysOfMonth.java [hunk 1]
```diff
@@ -7,14 +7,29 @@
...
-    public static void main(String[] args){
-        int year = Integer.parseInt(args[0]);
-        int month = Integer.parseInt(args[1]);
-        // Buggy output
-        System.out.printf("Month of %d/%d has %d days\n",
-        		month, year, daysofmonth(month, year));
+  public static void main(String[] args){
+    int year = Integer.parseInt(args[0]);
+    int month = Integer.parseInt(args[1]);
+    // Buggy output
```
Comment (ordovicia) [inline DaysOfMonth.java]: Please remove this comment.
